[MKT-475]: feat/ Christmas Campaign
internxt/website pull request #1170
Opened 2024-12-04 08:07 UTC by jaaaaavier

2024-12-05 15:27 UTC, xabg2 requested changes

2024-12-05 15:27 UTC, xabg2 commented on src/components/lifetime/PriceBannerForCampaigns.tsx
> +          <div className="min-width-[521px], min-height-[320px] flex items-center justify-center">
Remove the comma

2024-12-05 15:28 UTC, jaaaaavier commented on src/components/lifetime/PriceBannerForCampaigns.tsx
> +          <div className="min-width-[521px], min-height-[320px] flex items-center justify-center">
Done

2024-12-10 13:53 UTC, xabg2 approved these changes

2024-12-12 09:25 UTC, merged