Feat/use local currency for us
internxt/website pull request #74
Opened 2022-09-21 21:03 UTC by masterprog-cmd

Added getLocation function and changed symbols depending on country payment type

2022-09-22 06:54 UTC, sg-gs requested changes

2022-09-22 06:54 UTC, sg-gs commented on pages/pricing.js
> +        ip: "136.127.209.48"
what is this hardcoded ip?

2022-09-22 06:54 UTC, sg-gs commented on lib/utils.ts
> +  return axios.post(`${process.env.NEXT_PUBLIC_BRIDGE_URL}/gateway/uuid`, { email },
NEXT_PUBLIC_BRIDGE_URL -> NEXT_STORAGE_API_URL

2022-09-22 06:54 UTC, sg-gs commented on pages/pricing.js
> +      .then(data => {
add a `catch`

2022-09-22 07:00 UTC, masterprog-cmd commented on pages/pricing.js
> +        ip: "136.127.209.48"
It's a test only, I eliminate it

2022-09-23 11:10 UTC, sg-gs requested changes

2022-09-23 11:10 UTC, sg-gs commented on pages/pricing.js
> +      })
missing a `catch` here.

2022-09-23 11:13 UTC, masterprog-cmd commented on pages/pricing.js
> +      })
I have forgotten about him again

2022-09-23 16:15 UTC, sg-gs commented
Pending to test it via VPN. I will return with the result once tested. Apart from that, LGTM.

2022-09-23 16:20 UTC, sg-gs commented
Feedback: Be careful with the environment variables that change. As there is more than one environment variable appearing as new or being renamed. I have updated the PR's description with those changes.

2022-09-26 06:09 UTC, sg-gs approved these changes

2022-09-26 06:09 UTC, merged